### PR TITLE
Updated ExiftoolImageParser to use ImageMetadataExtractor for parsing tiff files

### PR DESCRIPTION
**Pull request by alexandraleahu**
Updated ExiftoolImageParser to use ImageMetadataExtractor for parsing tiff files

### CODE REVIEW

**Comment by rgauss** [comment]
In `pom.xml`, can you update the `version` to include the new date, i.e. `1.6-20160315` and change `tika.version` to `1.6` since 1.6-SNAPSHOT is no longer available in the Apache Maven snapshot repo?

**Comment by chrismattmann** [comment]
Ray we can't use the o.a.tika namespace if it's not in Tika or apache

**Comment by alexandraleahu** [comment]
I updated the versions in pom.xml

**Comment by rgauss** [comment]
> Ray we can't use the o.a.tika namespace if it's not in Tika or apache

Hi @chrismattmann, could you point me to more details on this?

We always intended (and still do) to contribute this to Tika but as I recall questions arose on the dev lists and Apache JIRA that needed to be addressed before contributing which were easier to evaluate in a working project rather than in those forums.

Unfortunately we won't have time to evaluate and address the impact of either changing the namespace or contributing to Tika in the short term, so unless we could drop it virtually as is on a branch or something we may have to make it closed source for now.

**Comment by chrismattmann** [comment]
yeah @rgauss the thing is we're not supposed to use o.a. namespace for non Apache projects. If this is really an Alfresco tool that you guys don't intend to contribute to Apache Tika anytime soon, then options are to take it down (closed source I guess) or to contribute to Apache. But we especially can't use the namespace but that would indicate it's an ASF project. cc @gagravarr

**Comment by rgauss** [comment]
We'll make this repo private and will contribute in a fork of Apache/tika shortly.

**Pull request merged**
